### PR TITLE
Use JCS to cache authenticated IRODSAccount object

### PR DESCRIPTION
**Pull request by hurngchunlee**
Hi,

Just took the liberty of making a pull request.  This is an implementation to cache IRODSAccount credential in the irons-webdav framework, using [Apache Commons JCS](https://commons.apache.org/proper/commons-jcs/).

The validity of the cache is configurable via the file: src/main/resources/cache.ccf

Comments and suggestions are welcomed.

Cheers, Hong

### CODE REVIEW

**Comment by michael-conway** [comment]
thanks...taking a look

**Comment by hurngchunlee** [comment]
Hi Mike,

Just saw a new RC1 release of WebDav with the enterprise key of Milton included.  Very nice!!  But I guess this pull request is not included.

Since our project is now relying on this patch, I wonder if it will be a chance to have it merged into a future release? Thanks!

Hong

**Comment by michael-conway** [comment]
Hi Hong,

Yes, I started to review it but wasn't sure what JCS was, etc.  I need 
to take a look at it.

Cheers
MC

**Comment by hurngchunlee** [comment]
Hi Mike,

I just merged the changes made for release 4.0.2.5-RC1 with the JCS patch to resolve conflicts.  Looking forward your update for future release, and hopefully the patch will be integrated.  Thanks!

Hong

**Comment by michael-conway** [comment]
Sure!  I hope to get back to WebDav in the next week or so.  I'm off 
doing other API at the moment.
MC

**Comment by hurngchunlee** [comment]
Hi Mike,

I suppose (and hope) that you haven't gotten or spent time on this issue, as I would like to withdraw this pull request.  The main reason is that we found a better way to implement the same feature, and it's by extending a jargon-core classe.  This approach does not require any code changes in irods-webdav, nor in jargon-core.  Furthermore, it's immediately applicable to also irods-rest and other webapps using jargon to interact with iRODS.

This extension is packed in a jar file. It is available [here](https://github.com/donders-research-data-management/rdm-jargon-authcache) on GitHub, with a short README about how it is implemented. It has been tested to be working with both irods-webdav and irods-rest.  If you find it's interesting, we are very happy to share it with you as well as the iRODS community.

I am closing this pull request now.  Thank you any way for your attention to our request.  

Hong

**Pull request closed without merging**
